name: Develop
author: liert
version: '${project.version}'
main: com.github.liert.Develop
description: This is a Minecraft plugin development assistant plugin.
commands:
  develop:
    description: "/develop"